### ISSUE TITLE
cannot parse x-www-form-urlencoded in the current way

### ISSUE THREAD

**Issue by yeliex** [helapkg/hela#56]
json parsed error when `Content-Type = application/x-www-form-urlencoded`

example: 

```
// POST data
const a = {
  a: 123,
  b: {
    c: 123
  }
}

// result
a={
  a: 123,
  b[c]: 123
}
```

**Comment by tunnckoCore** [comment]
Not sure enough, but will close.

**Comment by tunnckoCore** [comment]
Actually. Reopening, because I'll (or if you want) push one new test and will see if something is wrong.

edit: [this one](https://github.com/tunnckoCore/koa-better-body/blob/master/test/urlencoded.js#L30-L37) but without the `limit` and should be successfull

**Comment by yeliex** [comment]
actuallt it caused by the parser package and i had push a pr to solve it: use co-body instead 

it is a temporary solution

**Comment by tunnckoCore** [comment]
`co-body` uses `qs` module, not the builtin one that's why it works and you can pass different qs parsing module to `app.querystring`.

I'm not responsible for other's shits (i'm not talking to you, i dont know you) - I give flexibility and give "200%" (haha) coveraged packages.

_edit: All we can do is to add some notice to the readme for users to be aware of that. :) Wanna PR?_
